import Game.Metadata

World "Algebra"

Level 1

Title "Pascal's Rule"

namespace Algebra

Introduction
"
Pascal's triangle is generated by a remarkable rule.

Every entry is the sum of the two entries above it.
"

/--
`choose n k` is the binomial coefficient `(n choose k)`, i.e. the number of groups that can be made
of size `k` from a set of size `n`.

Do NOT attempt `rw [choose]`, it will not help in solving any of the problems.
Use one of the identities provided to manipulate expressions involve `choose`
-/
DefinitionDoc Game.Common.AlgebraDefs.choose as "choose" in "Algebra"

/--
Pascal's Rule:
```
choose (n+1) (k+1) = choose n k + choose n (k+1)
```

Every entry is the sum of the two entries above it.
-/
TheoremDoc Algebra.pascal_rule as "pascal_rule" in "Algebra"

Statement
  (n k : Nat) : choose (n + 1) (k + 1) = choose n k + choose n (k + 1) := by
  exact pascal_rule n k

NewTheorem Algebra.pascal_rule
NewDefinition Game.Common.AlgebraDefs.choose
NewTactic rw nth_rewrite exact «repeat» apply

end Algebra
